export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST" 
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS" 
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL" 

export const PRODUC_DETAILS_REQUEST = "PRODUC_DETAILS_REQUEST" 
export const PRODUC_DETAILS_SUCCESS = "PRODUC_DETAILS_SUCCESS" 
export const PRODUC_DETAILS_FAIL = "PRODUC_DETAILS_FAIL" 


export const CLEAR_ERRORS = "CLEAR_ERRORS"